export interface NeubauProjekt {
    // Projekt
    wohnflaeche: number;
    anzahlWohnungen: number;
    energiestandard: Energiestandard;
    konstruktion: Konstruktion;
    zertifizierung: Zertifizierung;
    // Neubau input
    kellergeschossIn: Kellergeschoss;
    stellplaetzeIn: Stellplaetze;
    aufzugsanlageIn: Aufzugsanlage;
    barrierefreiheitIn: BarrierefreiesBauen;
    dachbegruenungIn: Dachbegruenung;
    baustellenlogistikIn: Baustellenlogistik;
    aussenanlagenIn: Aussenanlagen;
    grundstuecksbezogeneKosten: number;
    baunebenkostenKeinFin: number;
    // Neubau output
    kellergeschossOut: number;
    stellplaetzeOut: number;
    redGarageOut: number;
    aufzugsanlageOut: number;
    barrierefreiheitOut: number;
    dachbegruenungOut: number;
    baustellenlogistikOut: number;
    aussenanlagenOut: number;
    energetischerStandard: number;
    // Dalehen
    kalkRealzins: number;
    kreditlaufzeit: number;
    kfWDarlehen: KfWDarlehen;
    bankDarlehen: BankDarlehen;
    // Output
    gestehungskosten: number;
    nrKredit: number;
    sollzinsKfw: number;
    gesamtgestehungskosten: number;
    restsumme: number;
    afKfw: number;
    afBank: number;
    annuitaetKfW: number;
    annuitaetBank: number;
    efKfW: number;
    efBank: number;
    gbAnnuitaet: number;
    gbEfd: number;
    // Zusammenfassung Ergebnisse
    kfwKredit: number;
    kfwKreditM2: number;
    bankKredit: number;
    bankKreditM2: number;
    finanzierungskostenKfw: number;
    finanzierungskostenKfwM2: number;
    finanzierungskostenFinanzmarkt: number;
    finanzierungskostenFinanzmarktM2: number;
    investitionskosten: number;
    investitionskostenM2: number;
    gInvestition: number;
    gInvestitionM2: number;
    gFinanzierung: number;
    gFinanzierungM2: number;
    // Vergleichsrechnung
    ohneKfw: number;
    ohneKfwM2: number;
    mitKfw: number;
    mitKfwM2: number;
}
